filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/**/*.log
      - /storage/volumes/**/*.log
    fields:
      service: green-worker-2
output.logstash:
  hosts: ["logstash.auto-deploy.net:9006"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
